# Demo: Traine a machine learning model using a MNIST dataset using the Keras API.

1. Load a prebuilt dataset.
1. Build a neural network machine learning model that classifies images.
2. Train this neural network.
3. Evaluate the accuracy of the model.

In [2]:
#### Copyright 2019 The TensorFlow Authors.

# Import TensorFlow
import tensorflow as tf
#print("TensorFlow version:", tf.__version__)

2025-03-18 11:50:32.303508: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1742295032.351667   47434 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1742295032.366043   47434 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1742295032.401659   47434 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1742295032.401703   47434 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1742295032.401710   47434 computation_placer.cc:177] computation placer alr

### Step-01:  Load dataset
[Hints] Load and prepare the MNIST dataset. The pixel values of the images range from 0 through 255. Scale these values to a range of 0 to 1 by dividing the values by `255.0`. This also converts the sample data from integers to floating-point numbers:

In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

### Step-02: Build a machine learning model
[Hints] Build a `tf.keras.Sequential` model: [`Sequential`](https://www.tensorflow.org/guide/keras/sequential_model) is useful for stacking layers where each layer has one input [tensor](https://www.tensorflow.org/guide/tensor) and one output tensor. Layers are functions with a known mathematical structure that can be reused and have trainable variables. Most TensorFlow models are composed of layers. This model uses the [`Flatten`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Flatten), [`Dense`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense), and [`Dropout`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout) layers.

In [6]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/home/somnath/anaconda3/lib/python3.12/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
2025-03-18 11:50:40.318393: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.04017692,  0.02126096, -0.26877993,  0.37898597, -0.4618035 ,
         0.5493813 , -0.56967896, -0.24838102, -0.56001455, -0.82947826]],
      dtype=float32)

In [8]:
# [TODO] Use `tf.nn.softmax` function converts these logits to *probabilities* for each class: 
tf.nn.softmax(predictions).numpy()

array([[0.11562537, 0.11345876, 0.08489358, 0.16225421, 0.06999157,
        0.19239676, 0.0628342 , 0.0866431 , 0.06344439, 0.04845813]],
      dtype=float32)

In [9]:
# [TODO] Define a loss function for training using `losses.SparseCategoricalCrossentropy`: This loss is equal to the negative log probability of the true class: 
# The loss is zero if the model is sure of the correct class.
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

1.6481956

In [11]:
# [TODO] Before you start training, configure and compile the model using Keras `Model.compile`. Set the 
# optimizer class to adam, set the loss to the loss_fn function you defined earlier, and specify a metric 
# to be evaluated for the model by setting the `metrics` parameter to `accuracy`.
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

### Step-03:  Train and evaluate your model
[Hints] Use the `Model.fit` method to adjust your model parameters and minimize the loss: 

In [13]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2025-03-18 11:50:41.329242: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 7ms/step - accuracy: 0.8596 - loss: 0.4886
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9549 - loss: 0.1488
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9677 - loss: 0.1091
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - accuracy: 0.9747 - loss: 0.0869
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9771 - loss: 0.0739


In [14]:
# [TODO] `Model.evaluate` method checks the model's performance, usually on a validation set and test set
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 4ms/step - accuracy: 0.9787 - loss: 0.0734


[0.07341164350509644, 0.9786999821662903]

The image classifier is now trained to ~98% accuracy on this dataset.

In [16]:
# [TODO] model to return a probability, you can wrap the trained model, and attach the softmax to it:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.2917582e-08, 1.2394368e-08, 1.4506104e-05, 3.0013578e-05,
        3.9617892e-12, 6.5451324e-08, 1.4711671e-14, 9.9995482e-01,
        4.8954153e-08, 4.4262194e-07],
       [2.5550696e-08, 2.0089190e-05, 9.9997699e-01, 1.1637286e-06,
        2.0917741e-18, 1.1940884e-06, 1.6596206e-07, 2.2606636e-15,
        4.3799216e-07, 7.2251818e-13],
       [2.7688125e-07, 9.9807250e-01, 3.3434443e-04, 4.1636631e-06,
        1.7553113e-05, 5.6080171e-06, 1.5203401e-05, 1.1415941e-03,
        4.0595661e-04, 2.7735655e-06],
       [9.9979502e-01, 8.5747232e-10, 1.8162970e-04, 2.1357146e-06,
        4.2955079e-08, 2.7813905e-06, 4.0982241e-06, 7.3078882e-06,
        5.0440946e-08, 7.0385795e-06],
       [1.1886943e-04, 4.7715609e-08, 1.1518786e-05, 6.9945668e-07,
        9.8429573e-01, 1.2044981e-06, 1.3850405e-04, 8.4751390e-04,
        5.7537880e-05, 1.4528272e-02]], dtype=float32)>